[workspace]
resolver = "2"
members = [
    "apexsky",
    "apexsky_dma", "apexsky_dmalib", "apexsky_kmbox", "apexsky_navigator",
    "apexsky_overlay", "apexsky_proto",
]
default-members = ["apexsky_dma"]
